import React from "react";
import Pherosection from "../components/Products/Pherosection";
import Head from "next/head";
import Pfeatures from "../components/Products/Pfeatures";
import PInformation from "../components/Products/PInformation";

const projects = () => {
  return (
    <div>
    <Head>
      <title>Sigma Projects </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
   <Pherosection/>
   <Pfeatures/>
   <PInformation/>
   
    </main>
  </div>
  );
};

export default projects;
